### ISSUE TITLE
huboard badges

### ISSUE THREAD

**Issue by thescouser89** [huboard/huboard#271]
Introduce badges that can be included into a README.md. That badge will also link directly to the huboard board of that github project.

Similar to how Travis CI and others does it.

##

**Comment by cben** [comment]
:+1: to a badge with per-column-count as proposed on https://github.com/badges/shields/issues/118

Meanwhile it's possible to use the github #-of-open-issues badge with custom label and link leading to Huboard:

`[![mathdown HuBoard](https://img.shields.io/github/issues/cben/mathdown.svg?label=issues%20%28HuBoard%29)](https://huboard.com/cben/mathdown)`
=>
[![mathdown HuBoard](https://img.shields.io/github/issues/cben/mathdown.png?label=issues%20%28HuBoard%29)](https://huboard.com/cben/mathdown)
(actually that's a .png because github comments don't render the svg)

(use `github/issues-raw/` if you prefer the number without the word " open")

**Comment by bkerensa** [comment]
Do want badge

**Comment by benjamincharity** [comment]
:+1:
