### ISSUE TITLE
Implement GitLab support [$3,000]

### ISSUE THREAD

**Issue by elestedt** [huboard/huboard#276]
Implement GitLab support in HuBoard:

 - [ ] Add GitLab support to [ghee](https://github.com/huboard/ghee) huboard/ghee#26
 - [ ] Test and verify [huboard-web](https://github.com/huboard/huboard-web) works with the GitLab API

Original issue body:
> I've been trying to adapt huboard to work with GitLab for a little while now. I just realized that I'm in over my head both time and knowledge-wise. My ruby skills are lacking to say the least.

> Any chance of you integrating the ruby gitlab gem so that huboard has an option to connect to either system?
I found that NARKOZ has a ruby implementation of the gitlab api: https://github.com/NARKOZ/gitlab

**Comment by aiQon** [comment]
+1

**Comment by divmgl** [comment]
+1 PLEASE

**Comment by b-sh** [comment]
:+1:

**Comment by deanperry** [comment]
:+1:

**Comment by ClashTheBunny** [comment]
Just so others know, there is a kanban board for GitLab here:
https://gitlab.com/laboard/laboard

**Comment by rockneverdies55** [comment]
:+1:

**Comment by adestis-ds** [comment]
+1

**Comment by ch1na-d0ll** [comment]
+1

**Comment by gazsp** [comment]
+1

**Comment by slaFFik** [comment]
+1

**Comment by Ahimta** [comment]
Hi @rauhryan, @stanhu.

I've been working/studying this issue for a little while.
And I'm confident that I can make an elegant solution.
It will take me sometime (as all good things), and I don't pretend that it will be a walk in the park.

What makes these kind of issues challenging/interesting is that they deal with many
levels of abstraction. And they involve more than just code.
So implementing this feature isn't really that hard, but doing it in a clean way
without just slapping some code to make it work, IMHO, is what the issue is all about.

I see that @stanhu starterd working on this and he seems to be familiar
with both GitLab and GitHub APIs.
To be honest, I think that knowing these details isn't that all that significant in an issue of this size;
other factors will dominate.

I was thinking on working on this issue on my private repo and then rebase my branch
whenever I make some progress (e.g: finish Ghee GitLab support).

Anyways, as much as I would like to work on this issue, I think that @stanhu is more qualified than me,
and it will be best for the project that he works on this issue.

These some of the stuff I've been working on:
```markdown
# Current Authenticated User Attributes

## GitHub Specific (33)
- [ ] blog
- [ ] collaborators
- [ ] company
- [ ] disk_usage
- [ ] events_url
- [ ] followers
- [ ] followers_url
- [ ] following
- [ ] following_url
- [ ] gists_url
- [ ] gravatar_id
- [ ] hireable
- [ ] html_url
- [ ] location
- [ ] login
- [ ] organizations_url
- [ ] owned_private_repos
- [ ] plan.collaborators
- [ ] plan.name
- [ ] plan.private_repos
- [ ] plan.space
- [ ] private_gists
- [ ] public_gists
- [ ] public_repos
- [ ] received_events_url
- [ ] repos_url
- [ ] site_admin
- [ ] starred_url
- [ ] subscriptions_url
- [ ] total_private_repos
- [ ] type
- [ ] updated_at
- [ ] url

## GitLab Specific (18)
- [ ] can_create_group
- [ ] can_create_project
- [ ] color_scheme_id
- [ ] current_sign_in_at
- [ ] is_admin
- [ ] linkedin
- [ ] private_token
- [ ] projects_limit
- [ ] skype
- [ ] state
- [ ] theme_id
- [ ] twitter
- [ ] two_factor_enabled
- [ ] username
- [ ] website_url

## Both (6)
- [x] avatar_url
- [x] bio
- [x] created_at
- [x] email
- [x] id
- [x] name

## GitLab Changed (1)
- [x] html_url => 'https://gitlab.com/<username>'

## GitLab Copied Attributes (1)
- [x] updated_at => created_at

## GitLab Renamed Attributes (3)
- [x] is_admin => site_admin
- [x] username => login
- [x] website_url => blog


## GitLab Default Attributes (18)
- [ ] collaborators => 0
- [ ] company => ''
- [ ] disk_usage => 0
- [ ] followers => 0
- [ ] following => 0
- [ ] gravatar_id => ''
- [ ] hireable => false
- [ ] location => ''
- [ ] owned_private_repos => 0
- [ ] plan.collaborators => 0
- [ ] plan.name => ''
- [ ] plan.private_repos => 0
- [ ] plan.space => 0
- [ ] private_gists => 0
- [ ] public_gists => 0
- [ ] public_repos => 0
- [ ] total_private_repos => 0
- [ ] type => 'User'
```

```ruby
require 'gitlab'

module Ghee::Gitlab
  class Client

    def initialize(private_token, endpoint = 'https://gitlab.com/api/v3')
      @client = ::Gitlab.client(endpoint: endpoint, private_token: private_token)
    end

    def user(id = nil)
      ::Ghee::Gitlab::API::User.new(@client, id)
    end
  end
end
```

```ruby
module Ghee::Gitlab
  module API
    class User

      def initialize(client, id)
        @user_client = client.user(id)
        @client = client

        response = @user_client.to_hash
        @response = pick_changed_attrs(response)
          .merge(pick_copied_attrs(response))
          .merge(pick_github_attrs(response))
          .merge(pick_renamed_attrs(response))
      end

      def to_hash
        @response
      end

      def keys
        @user_client.ssh_keys || []
      end

      def [](key)
        @response[key]
      end

      private

      def pick_changed_attrs(response)
        {
          'html_url' => "https://gitlab.com/u/#{response['username']}"
        }
      end

      def pick_copied_attrs(response)
        {
          'updated_at' => response['created_at']
        }
      end

      def pick_github_attrs(response)
        {
          'avatar_url' => response['avatar_url'],
          'bio' => response['bio'],
          'created_at' => response['created_at'],
          'email' => response['email'],
          'id' => response['id'],
          'name' => response['name']
        }
      end

      def pick_renamed_attrs(response)
        {
          'site_admin' => response['is_admin'],
          'login' => response['username'],
          'blog' => response['website_url']
        }
      end
    end
  end
end
```

**Comment by rauhryan** [comment]
Thank you @Ahimta

This is very well thought out and very helpful.

This is the first time I've ever managed a bounty, so I'm not quite sure how it works, maybe there is something you and @stanhu can work out to share the bounty. 

It sounds like this is going to be a pretty decent undertaking, so maybe that's a good idea, I don't know. 

I will reach out to bountysource and see if there is already a precedent for something like this

Other than that, I am here to help in anyway I can, whether that's mentorship, answering questions about Ghee or HuBoard, helping you get up and running with the application, extending documentation, anything at all, please ask

Thank you both very much for your feedback and contributions

**Comment by warent** [comment]
If you care at all about backwards compatibility, I strongly advise against using the solution by @stanhu
I recommend a polymorphic solution with an optional parameter to declare source (Github, gitlab, etc.) upon instantiation. Interface the current Ghee solution with an extension library determined by the earlier mentioned parameter.

Then none of the functions have to be changed at all, and you can drop in other libraries for APIs (bitbucket? etc.) without having to backpeddle like this again.

If you give me a little bit I should be able to smash my keyboard for long enough until it works just like I described it; and it would be preferable to retain backwards compatibility. I already have huboard running on 0.0.0.0:5000 and ghee test environments.

Is this interesting to you @rauhryan ?

**Comment by hwinkel** [comment]
Is there any progress on that?

:+1:

**Comment by rauhryan** [comment]
@warent & @hwinkel 

Sorry for not getting back to you sooner. 

I unfortunately was unable to keep up with the work required to mentor @stanhu through this process. 

We only have a team of 2 developers right now and got way too busy supporting and maintaining the users that we currently have. 

I'm available to answer questions if someone wants to take another stab at it

**Comment by dosire** [comment]
@stanhu what do you suggest as the next step here?

**Comment by stanhu** [comment]
@dosire I'll see if I can push this along further in the next few weeks. I last ran into questions about how to deal with OAuth2 support between GitHub and GitLab:

https://github.com/huboard/huboard-web/pull/157

**Comment by dosire** [comment]
OK, thanks @stanhu

**Comment by rauhryan** [comment]
@dosire @stanhu we got stalled out on how to handle the OAuth and being able to switch between GitLab and GitHub. 

We have a lot of places in the application that rely on the warden failure app to capture warden exceptions to display the correct error pages. 

I spiked out using multiple strategies with warden and was unable to get my head around how the whole stack works because it's very difficult to debug the back and handshake with the third party vendor. 

Switching to omniauth seems like a good move but then we lose the nice middleware and error handling that warden provides. 

Is it safe to say that everything is blocked on how to handle authentication?

Perhaps we need to write a warden strategy for GitLab?

**Comment by stanhu** [comment]
> Is it safe to say that everything is blocked on how to handle authentication?

I think there could be more progress made on the conversion of the API queries, but I think it's important to straighten this out before going further.

> Perhaps we need to write a warden strategy for GitLab?

Are you saying that you want to stick with warden or go with omniauth?

**Comment by rauhryan** [comment]
> Are you saying that you want to stick with warden or go with omniauth?

for right now we need to stick to warden because we rely on it for the error handling and transitioning between OAuth permission scopes. 

I spent several days spiking out different login strategies and couldn't figure out a great way to make it all work right with omniauth

https://github.com/huboard/huboard-web/compare/8fbe0ab...5cf50bd

omniauth is very basic and leaves all the storage options up to you to implement, I'm actually not sure what the best way to move forward is and I'm open to ideas

**Comment by dosire** [comment]
@stanhu It would be great if you can have a look at this. I know you're busy but integrating with Huboard would complete an important part of our scope https://about.gitlab.com/direction/#scope

**Comment by Ermesx** [comment]
👍

**Comment by lasercar** [comment]
👍

**Comment by donhui** [comment]
:+1:

**Comment by dosire** [comment]
There has not been much activity on this bounty for months.

As GitLab Inc. we'll focus instead on https://gitlab.com/gitlab-org/gitlab-ce/issues/17907

Having https://gitlab.com/gitlab-org/gitlab-ce/issues/17907 means we'll probably not ship Huboard with GitLab. 

This also means that @stanhu from GitLab Inc. will not be working on this issue nor can we spend a lot of time reviewing it.

I therefore propose to close the bounty unless someone is already working on it and objects.

**Comment by GildedHonour** [comment]
What's the status of this, is anybody working on it? Is this bounty on? Can I start working on it?

**Comment by stanhu** [comment]
Today GitLab 8.11 shipped with a built-in Issue Board feature (https://about.gitlab.com/2016/08/22/gitlab-8-11-released/), so GitLab is no longer interested in supporting this bounty. Thanks, everyone, for your interest.
