### ISSUE TITLE
Feature Request: Convert Issues to Pull Requests

### ISSUE THREAD

**Issue by klcodanr** [huboard/huboard#309]
There are a number of tools for converting issues to pull requests, but it would be **really** helpful to be able to do this through the Huboard UI instead of having to add another third party into our development process.

Here are some of the tools available:
https://github.com/github/hub
http://issue2pr.herokuapp.com/

**Comment by dahlbyk** [comment]
Closing this. We suggest creating PRs that "Close #xxx" rather than converting because closed PRs cannot be reopened if the issue was not actually resolved sufficiently by the converted-to-PR code. We are actively discussing how to improve the UX around issue/PR combinations to avoid needing to manipulate both within HuBoard.
