### ISSUE TITLE
Huboard asks for wider permissions than it needs

### ISSUE THREAD

**Issue by betamatt** [huboard/huboard#468]
The repository permission the app asks for is basically a full-admin mode with access to settings and the ability to write to git. Why is that level of access required? Would it be possible to authorize at a lower level and then request permission upgrades when features that use them are enabled?

**Comment by jamie** [comment]
Yeah... blame Github for that one. The available [https://developer.github.com/v3/oauth/#scopes](scopes) are rather broad-grained.

**Comment by diophore** [comment]
Yeah, this is a GitHub issue - affects every integration. I hate it too.

**Comment by ehausen** [comment]
https://developer.github.com/changes/2015-06-24-api-enhancements-for-working-with-organization-permissions/

**Comment by rauhryan** [comment]
@betamatt - we are aware that the permissions model is very broad

Please refer to https://github.com/huboard/huboard/issues/203#issuecomment-21295111 for our thoughts on the issue. 

dear-github/dear-github#113 <- has a great write up and a great discussion around the issue. 

I'm going to close the issue, because it's not something that is actionable by anyone on our team. 

As soon as GitHub implements finer grained permissions we will rework our OAuth policies. 

Thanks, 

 - Ryan
