### ISSUE TITLE
Filter closed issues in "Milestones" view

### ISSUE THREAD

**Issue by tednyberg** [huboard/huboard#517]
I think it would be great to have an option under "Filters" for showing/hiding closed issues in "Milestones" view. Unless I'm overlooking some other way of accomplishing this?

I think this makes sense instead of having to "archive" issues in order for them to be hidden in the milestones view.

PS. I love HuBoard! :) DS.

**Comment by dahlbyk** [comment]
Not sure how this slipped past us, but I agree: https://github.com/huboard/huboard/issues/648 :wink:

We already have a lot of filter options, but we might be able to add one to help with this. Or we could just always hide closed issues from Milestones, since it's really more of a planning view anyway?

**Comment by discorick** [comment]
I am a fan of just hiding the closed issues altogether. Thinking on it, there doesn't seem much reason for them to exist in that view anyways.
