### ISSUE TITLE
Error when closing an issue

### ISSUE THREAD

**Issue by bs85** [huboard/huboard#645]
We have self-hosted huboard deployed on a heroku server. I can't give you more details as I don't have access to the server right now, if you need more info on version / whatever, let me know and I'll dig.

From the main issues page, if I click on an open issue, write a message and click on "mark as closed", the message is sent to github and the issue closed properly, but the interface freezes and a page refresh is required.

Simply posting a message works, but closing an issue without a message does the same thing.

I don't have sourcemaps but the code that fails is `this.get("socket").publish({meta:a,payload:r})}`

![hb_bug](https://cloud.githubusercontent.com/assets/3041431/14539783/1f65580c-0282-11e6-9b97-93ae79335c75.png)

**Comment by discorick** [comment]
Looks like the `socket` is missing... Is this consistent behavior (does a refresh fix it)? Also do you know what commit you are running on ?

**Comment by bs85** [comment]
Refresh doesn't fix it, it happens 100% of the time.

I'll get back to you when I can get the into about the commit we're running, thanks for the quick reply

**Comment by dahlbyk** [comment]
@bs85 we may have discovered this same issue ourselves and not realized it: https://github.com/huboard/huboard/issues/647. Try updating to `master` that would include https://github.com/huboard/huboard-web/pull/271?

**Comment by discorick** [comment]
@bs85, I think @dahlbyk is right - I missed referencing this issue to the Pull Request

**Comment by rauhryan** [comment]
Actually I think his issue was fixed here https://github.com/huboard/huboard-web/pull/268/files#diff-5bb7f4bc8d062dea46291a11be6e7811R9

It's not well documented but you can configure HuBoard to self host Faye as a middleware in the Rails application and get the real time sockets to work in your deployment.

## Prerequisites

  * You will need to have a redis instance available. If you are hosting on Heroku you can use any of the free plans (We use the redis cloud plan)
  * HuBoard expects an ENV variable `REDIS_URL` to be present for this to work, I think Redis Cloud will set this for you

## Next you need to have two ENV variables set correctly. 

```
SELF_HOST_FAYE=true
SOCKET_BACKEND=/site/pubsub
```

You also want to make sure that `SIDEKIQ` is not set, otherwise you need to run a sidekiq worker.

**Comment by discorick** [comment]
> I click on an open issue, write a message and click on "mark as closed", the message is sent to github and the issue closed properly, but the interface freezes and a page refresh is required.

@rauhryan its the close issue bug

**Comment by bs85** [comment]
Thank you for the details!

I hadn't had the time to investigate, I'll try to update and add redis ASAP

**Comment by bs85** [comment]
Everything works with the latest release and the faye config! cheers guys

**Comment by azappella** [comment]
FYI, the latest release that we deployed refers to https://github.com/huboard/huboard/commit/ea313dc05dc49f7a0dbf5bde77bf681bd5783345
